### ISSUE TITLE
DeveloperGuide broken

### ISSUE THREAD

**Issue by yongxiangng** [AY2122S1-CS2103-T16-4/tp#107]
![image](https://user-images.githubusercontent.com/60974969/139510904-955e9ebb-59d0-4294-b5ea-1a1c007e3e27.png)
![image](https://user-images.githubusercontent.com/60974969/139510919-b5782b0d-8a36-48d7-85bb-71fc131fbe51.png)
Someone broke the DeveloperGuide

**Comment by IceWizard4902** [comment]
This is due to me updating some IntellJ settings locally to resolve the trailing spaces error.

Will look into this

**Comment by yongxiangng** [comment]
![image](https://user-images.githubusercontent.com/60974969/139524761-01c29efe-c7a4-497c-a3c3-f46912c511da.png)

These parts broke as well
