### ISSUE TITLE
[PE-D] Result message for Chaining commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-4/tp#124]
Result message for chaining commands: `&&` will show multiple results for each of the command executed, however, when theres an error in the midst of the chaining, the previous successful results will not be shown in the message box, but instead, only the error message is shown. This would make it unclear as to which part of the codes contains the error if I were to do multiple similar commands.

A successful chaining command (e.g. `find xiaoming && delete 1`, where xiaoming is in the address book and index 1 exists):

![chaining-success](https://raw.githubusercontent.com/sharmainec/ped/main/files/9a5b96fe-f531-4367-b251-dc17fa81ecac.png)

A not successful chaining command (e.g. `find xiaoming && delete 1 && find xiaoli && delete 2 && list`, where xiaoming is in the address book and theres only 1 xiaoli, so index 2 does not exist): 

![chaining-failed](https://raw.githubusercontent.com/sharmainec/ped/main/files/3b476ef8-2a30-4a17-85d3-61bf1751a659.png)

In this scenario, commands before `delete 2` has been executed successfully, which means that xiaoming is already deleted. But the error message does not show that xiaoming has already been deleted.

Proposed change: Show the results message of the commands that have been executed, followed by the error message.

Would be even better if you can specify which results message is for which command, e.g. find xiaoming command: 1 person listed

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: sharmainec/ped#2

**Comment by nzixuan** [comment]
Low severity bug. Due to the exception handling of base ab3 it is difficult to implement such a feature without massively changing the code base.
