### ISSUE TITLE
Implement new feature: Instructions/Tips/Command List

### ISSUE THREAD

**Issue by dannytayjy** [AY2122S1-CS2103-T16-4/tp#55]
As a first time user, I can easily find the documentation on the list of commands available so that I can try those commands.

As a new user wanting to integrate the app into my routine, I want a tutorial and documentation which teaches me all the features/commands of the app and is sorted into basic, intermediate, and advanced commands, this will help me get more comfortable with using the app.

As a relatively new user, I can see new tips so that I get to know the application better.

**Comment by IceWizard4902** [comment]
Feature not implemented in v1.3
